#!/usr/bin/env python3
"""Regenerate the symbol-rename block in src/external/sbc_config.h.

Maintainer tool. Run it after tools/sync_sbc.py pulls a new upstream
snapshot, or when a later phase enables the encoder or the PLC.

    python tools/gen_sbc_symbol_renames.py                    # print the block
    python tools/gen_sbc_symbol_renames.py --apply            # rewrite the header
    python tools/gen_sbc_symbol_renames.py --libbt <libbt.a>  # report real collisions

Why this exists
---------------
arduino-esp32's prebuilt libbt.a links Bluedroid's own copy of this exact
codec, and it exports far more than the documented entry points: the
internal helpers (OI_SBC_ReadHeader, crc8_narrow, dct2_8, shift_buffer, …)
are non-static too. Any sketch using A2DP links libbt.a, so every one of
those is a duplicate-symbol risk.

Hand-maintaining that list does not work — an upstream snapshot that makes
one more helper non-static would break the link with no warning. So we
compile the vendored tree with the renames disabled, ask the linker's own
view of it via nm, and rename everything it reports.

The renames live in sbc_config.h, which is our replacement for Bluedroid's
common/bt_target.h. Every vendored file includes that, so the prefix applies
without any vendored file being modified. See SPEC.md §11.3.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import shutil
import subprocess
import sys
import tempfile

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC_DIR = REPO_ROOT / "src"
VENDOR_DIR = SRC_DIR / "external" / "sbc"
CONFIG_PATH = SRC_DIR / "external" / "sbc_config.h"

PREFIX = "pcmflowbt_"

BEGIN_MARKER = "/* BEGIN generated by tools/gen_sbc_symbol_renames.py */"
END_MARKER = "/* END generated by tools/gen_sbc_symbol_renames.py */"

# Directories compiled for the symbol sweep. The encoder and the PLC are
# swept too, even though they are not built yet, so enabling them in a later
# phase does not silently reintroduce collisions.
SWEEP_DIRS = ["decoder/srce", "encoder/srce", "plc"]

EXTRA_SOURCES = [SRC_DIR / "external" / "sbc_port.c"]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--apply", action="store_true",
                        help="Rewrite the generated block in sbc_config.h.")
    parser.add_argument("--cc", default="gcc", help="Host compiler (default: gcc).")
    parser.add_argument("--nm", default="nm", help="nm for the host objects (default: nm).")
    parser.add_argument("--libbt", metavar="PATH",
                        help="A libbt.a to intersect against, to report real collisions.")
    parser.add_argument("--libbt-nm", default=None,
                        help="nm for libbt.a (default: xtensa-esp32-elf-nm, then --nm).")
    return parser.parse_args()


def sources() -> list[pathlib.Path]:
    out: list[pathlib.Path] = []
    for rel in SWEEP_DIRS:
        d = VENDOR_DIR / rel
        if not d.is_dir():
            raise SystemExit(f"error: {d} not found — run tools/sync_sbc.py first")
        out.extend(sorted(d.glob("*.c")))
    out.extend(p for p in EXTRA_SOURCES if p.is_file())
    return out


def compile_all(cc: str, outdir: pathlib.Path) -> list[pathlib.Path]:
    """Compile every vendored source with renames off and all parts enabled."""
    objects: list[pathlib.Path] = []
    failures: list[str] = []
    for src in sources():
        obj = outdir / (src.name + ".o")
        cmd = [
            cc, "-c", "-O1", "-w",
            "-DPCMFLOWBT_SBC_NO_RENAME=1",
            "-DSBC_DEC_INCLUDED=1", "-DSBC_ENC_INCLUDED=1", "-DPLC_INCLUDED=1",
            f"-I{SRC_DIR}", f"-I{SRC_DIR / 'external'}",
            "-o", str(obj), str(src),
        ]
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            # The encoder and the PLC still reference Bluedroid internals that
            # only their own phase will supply. Their symbols are picked up
            # from whatever does compile; report the rest rather than failing.
            failures.append(f"{src.relative_to(REPO_ROOT)}: {result.stderr.strip().splitlines()[0]}")
            continue
        objects.append(obj)
    if failures:
        print("Skipped (did not compile in this configuration):", file=sys.stderr)
        for line in failures:
            print(f"  {line}", file=sys.stderr)
        print(file=sys.stderr)
    if not objects:
        raise SystemExit("error: nothing compiled")
    return objects


def defined_symbols(nm: str, paths: list[pathlib.Path]) -> set[str]:
    result = subprocess.run(
        [nm, "-g", "--defined-only", *[str(p) for p in paths]],
        check=True, capture_output=True, text=True,
    )
    out: set[str] = set()
    for line in result.stdout.splitlines():
        parts = line.split()
        if len(parts) >= 3 and parts[1] in "TDRBWV":
            out.add(parts[2])
    return out


def render_block(symbols: set[str]) -> str:
    names = sorted(s for s in symbols if not s.startswith(PREFIX))
    width = max(len(n) for n in names)
    lines = [
        BEGIN_MARKER,
        "/* Every global symbol the vendored tree defines, as reported by nm.",
        " * Regenerate with tools/gen_sbc_symbol_renames.py after a sync. */",
    ]
    lines += [f"#define {n:<{width}} {PREFIX}{n}" for n in names]
    lines.append(END_MARKER)
    return "\n".join(lines) + "\n"


def apply_block(block: str) -> None:
    text = CONFIG_PATH.read_text(encoding="utf-8")
    pattern = re.compile(
        re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER) + r"\n",
        re.DOTALL,
    )
    if not pattern.search(text):
        raise SystemExit(
            f"error: markers not found in {CONFIG_PATH}; add\n"
            f"  {BEGIN_MARKER}\n  {END_MARKER}\nwhere the block belongs"
        )
    CONFIG_PATH.write_text(pattern.sub(lambda _: block, text), encoding="utf-8")


def main() -> int:
    args = parse_args()

    with tempfile.TemporaryDirectory() as tmp:
        objects = compile_all(args.cc, pathlib.Path(tmp))
        symbols = defined_symbols(args.nm, objects)

    print(f"{len(symbols)} global symbols across {len(objects)} objects", file=sys.stderr)

    if args.libbt:
        nm = args.libbt_nm or shutil.which("xtensa-esp32-elf-nm") or args.nm
        libbt = defined_symbols(nm, [pathlib.Path(args.libbt)])
        collisions = sorted(symbols & libbt)
        print(f"{len(collisions)} of them are also defined in {args.libbt}:", file=sys.stderr)
        for name in collisions:
            print(f"  {name}", file=sys.stderr)
        print(file=sys.stderr)

    block = render_block(symbols)
    if args.apply:
        apply_block(block)
        print(f"Rewrote the generated block in {CONFIG_PATH}.", file=sys.stderr)
    else:
        print(block, end="")
    return 0


if __name__ == "__main__":
    sys.exit(main())
