#!/usr/bin/env python3
"""Refresh the vendored SBC codec snapshot under src/external/sbc/.

Maintainer tool. Not invoked from CI (PCMFlowBluetooth adopts upstream-
tracking level L0; see SPEC.md §11.5). Run by hand when you want to pull
in a newer upstream snapshot:

    python tools/sync_sbc.py --apply                     # sparse-clone ESP-IDF
    python tools/sync_sbc.py --apply --from ../esp-idf   # use a local checkout

Without --apply the script only reports what would change.

Upstream is ESP-IDF's components/bt/host/bluedroid/external/sbc/, which is
itself AOSP-derived:

    decoder/  Open Interface North America (2006) + AOSP (2014)  Apache-2.0
    encoder/  Broadcom Corporation (1999-2012)                   Apache-2.0
    plc/      Espressif Systems (2015-2021)                      Apache-2.0

Two things have to be arranged for the tree to build as an Arduino library,
and both are handled here so that the vendored files stay byte-for-byte
verbatim:

1. `common/bt_target.h`. Every vendored .c/.h includes it to pick up the
   SBC_DEC_INCLUDED / SBC_ENC_INCLUDED / PLC_INCLUDED switches. We generate
   a shim at that path which forwards to our own src/external/sbc_config.h.
   That file also carries the symbol-rename macros that keep us from
   colliding with the OI_CODEC_SBC_* symbols arduino-esp32's libbt.a
   already exports (SPEC.md §11.3).

2. Cross-directory includes. Upstream is built with several -I paths; the
   Arduino library format only puts <library>/src on the include path.

   For quoted includes we emit, in every directory of the tree, a one-line
   shim header for each include that directory references but does not
   contain. GCC resolves #include "X" starting from the directory of the
   file doing the include, so the shim always wins.

   A few upstream files reach across directories with an *angle* include
   (<oi_codec_sbc_private.h>). Angle includes never consult the including
   file's own directory, so a neighbouring shim cannot catch them; those get
   a shim at src/ instead, which is the one directory Arduino does put on
   the include path. See SPEC.md §11.4.

Shims are wiped and regenerated on every --apply run, so they never drift
away from the verbatim files they sit next to.
"""

from __future__ import annotations

import argparse
import datetime as _dt
import os
import pathlib
import re
import shutil
import subprocess
import sys
import tempfile

UPSTREAM_URL = "https://github.com/espressif/esp-idf.git"
UPSTREAM_SUBDIR = "components/bt/host/bluedroid/external/sbc"

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC_DIR = REPO_ROOT / "src"
VENDOR_DIR = SRC_DIR / "external" / "sbc"
LOCK_PATH = SRC_DIR / "external" / "UPSTREAM.lock"

# The codec is self-contained in these directories. Nothing else from
# ESP-IDF is vendored.
VENDORED_DIRS = [
    "decoder/include",
    "decoder/srce",
    "encoder/include",
    "encoder/srce",
    "plc",
    "plc/include",
]

VENDORED_SUFFIXES = {".c", ".h", ".inc"}

# Generated, not vendored. Removed and rewritten on every --apply run so a
# stale shim can never survive an upstream layout change.
SHIM_MARKER = "/* Generated by tools/sync_sbc.py - do not edit. */"

# Path of our replacement for Bluedroid's build-configuration header,
# relative to VENDOR_DIR.
SBC_CONFIG_RELATIVE_TO_VENDOR = pathlib.PurePosixPath("../sbc_config.h")

# Includes that resolve to a system header, never to a shim.
SYSTEM_INCLUDES: set[str] = set()

_INCLUDE_RE = re.compile(r'^[ \t]*#[ \t]*include[ \t]+"([^"]+)"', re.M)
_ANGLE_INCLUDE_RE = re.compile(r'^[ \t]*#[ \t]*include[ \t]+<([^>]+)>', re.M)


# ---------------------------------------------------------------------------
# Upstream acquisition


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Write the changes. Without it the script only reports them.",
    )
    parser.add_argument(
        "--from",
        dest="local",
        metavar="PATH",
        help="Use a local esp-idf checkout instead of cloning.",
    )
    parser.add_argument(
        "--ref",
        default="master",
        help="Upstream ref to clone when --from is not given (default: master).",
    )
    return parser.parse_args()


def resolve_source(args: argparse.Namespace, tmp: pathlib.Path) -> tuple[pathlib.Path, str]:
    """Return (path to the upstream sbc directory, commit SHA)."""
    if args.local:
        root = pathlib.Path(args.local).expanduser().resolve()
        src = root / UPSTREAM_SUBDIR
        if not src.is_dir():
            raise SystemExit(f"error: {src} not found — is {root} an esp-idf checkout?")
        sha = subprocess.run(
            ["git", "-C", str(root), "rev-parse", "HEAD"],
            check=True, capture_output=True, text=True,
        ).stdout.strip()
        return src, sha

    clone = tmp / "esp-idf"
    print(f"Cloning {UPSTREAM_URL} ({args.ref}, sparse) …")
    subprocess.run(
        ["git", "clone", "--filter=blob:none", "--no-checkout", "--depth", "1",
         "--branch", args.ref, UPSTREAM_URL, str(clone)],
        check=True,
    )
    subprocess.run(["git", "-C", str(clone), "sparse-checkout", "init", "--cone"], check=True)
    subprocess.run(["git", "-C", str(clone), "sparse-checkout", "set", UPSTREAM_SUBDIR], check=True)
    subprocess.run(["git", "-C", str(clone), "checkout"], check=True)
    sha = subprocess.run(
        ["git", "-C", str(clone), "rev-parse", "HEAD"],
        check=True, capture_output=True, text=True,
    ).stdout.strip()
    return clone / UPSTREAM_SUBDIR, sha


# ---------------------------------------------------------------------------
# Copy


def collect_upstream(src_root: pathlib.Path) -> dict[str, bytes]:
    """Map vendored-relative path -> file bytes."""
    out: dict[str, bytes] = {}
    for rel_dir in VENDORED_DIRS:
        d = src_root / rel_dir
        if not d.is_dir():
            raise SystemExit(f"error: upstream is missing {rel_dir}; layout changed?")
        for path in sorted(d.iterdir()):
            if not path.is_file() or path.suffix not in VENDORED_SUFFIXES:
                continue
            out[f"{rel_dir}/{path.name}"] = path.read_bytes()
    if not out:
        raise SystemExit("error: no files collected; layout changed?")
    return out


# ---------------------------------------------------------------------------
# Shim generation


def index_headers(files: dict[str, bytes]) -> dict[str, str]:
    """Map header basename -> vendored-relative path.

    There are no basename collisions across the SBC tree; the script asserts
    that rather than trusting it.
    """
    out: dict[str, str] = {}
    for rel in files:
        name = rel.rsplit("/", 1)[-1]
        if not name.endswith((".h", ".inc")):
            continue
        if name in out:
            raise SystemExit(
                f"error: duplicate header basename {name!r} "
                f"({out[name]} vs {rel}); the flat shim scheme no longer holds"
            )
        out[name] = rel
    return out


def collect_includes(files: dict[str, bytes]) -> dict[str, set[str]]:
    """Map vendored-relative directory -> set of quoted includes it references."""
    out: dict[str, set[str]] = {}
    for rel, data in files.items():
        directory = rel.rsplit("/", 1)[0]
        text = data.decode("utf-8", errors="replace")
        for inc in _INCLUDE_RE.findall(text):
            out.setdefault(directory, set()).add(inc)
    return out


def plan_shims(files: dict[str, bytes]) -> dict[str, str]:
    """Map vendored-relative shim path -> shim contents.

    A shim is needed whenever a directory references an include that does not
    resolve relative to that directory.
    """
    headers = index_headers(files)
    present = set(files)
    shims: dict[str, str] = {}

    for directory, includes in sorted(collect_includes(files).items()):
        for inc in sorted(includes):
            if inc in SYSTEM_INCLUDES:
                continue
            # Resolves relative to the including directory already?
            direct = os.path.normpath(f"{directory}/{inc}").replace(os.sep, "/")
            if direct in present:
                continue

            shim_path = f"{directory}/{inc}"
            basename = inc.rsplit("/", 1)[-1]
            shim_dir = pathlib.PurePosixPath(shim_path).parent

            if inc.endswith("bt_target.h"):
                # Bluedroid's build configuration. Forward to ours.
                target = os.path.relpath(
                    (pathlib.PurePosixPath(".") / SBC_CONFIG_RELATIVE_TO_VENDOR).as_posix(),
                    start=shim_dir.as_posix(),
                )
                note = "Bluedroid build configuration, replaced by ours."
            elif basename in headers:
                target = os.path.relpath(headers[basename], start=shim_dir.as_posix())
                note = f"Cross-directory include of {headers[basename]}."
            else:
                # Referenced by the encoder but supplied by Bluedroid, not by
                # the codec (stack/bt_types.h, osi/allocator.h). Our config
                # header carries the handful of definitions they provide.
                target = os.path.relpath(
                    (pathlib.PurePosixPath(".") / SBC_CONFIG_RELATIVE_TO_VENDOR).as_posix(),
                    start=shim_dir.as_posix(),
                )
                note = "Supplied by Bluedroid upstream; satisfied by our config header."

            shims[shim_path] = (
                f"{SHIM_MARKER}\n"
                f"/* {note} */\n"
                f'#include "{target}"\n'
            )

    return shims


def plan_root_shims(files: dict[str, bytes]) -> dict[str, str]:
    """Map src/-relative shim path -> contents, for angle-bracket includes.

    `#include <X>` never searches the including file's own directory, so the
    per-directory shims cannot catch it. Arduino puts `<library>/src` on the
    include path, so a shim there is the one place that works.

    Anything that is not a header we vendor is assumed to be a system header
    and left alone.
    """
    headers = index_headers(files)
    shims: dict[str, str] = {}

    for rel, data in sorted(files.items()):
        text = data.decode("utf-8", errors="replace")
        for inc in _ANGLE_INCLUDE_RE.findall(text):
            basename = inc.rsplit("/", 1)[-1]
            if basename not in headers:
                continue  # system header
            target = f"external/sbc/{headers[basename]}"
            shims[inc] = (
                f"{SHIM_MARKER}\n"
                f"/* Angle-bracket include of {target} — see tools/sync_sbc.py. */\n"
                f'#include "{target}"\n'
            )
    return shims


# ---------------------------------------------------------------------------
# Write


def read_current() -> dict[str, bytes]:
    out: dict[str, bytes] = {}
    if not VENDOR_DIR.is_dir():
        return out
    for path in VENDOR_DIR.rglob("*"):
        if path.is_file():
            out[path.relative_to(VENDOR_DIR).as_posix()] = path.read_bytes()
    return out


def report(current: dict[str, bytes], desired: dict[str, bytes]) -> bool:
    added = sorted(set(desired) - set(current))
    removed = sorted(set(current) - set(desired))
    changed = sorted(k for k in set(desired) & set(current) if current[k] != desired[k])

    for label, items in (("add", added), ("remove", removed), ("update", changed)):
        for item in items:
            print(f"  {label:6} {item}")
    if not (added or removed or changed):
        print("  (no changes)")
    return bool(added or removed or changed)


def write_tree(desired: dict[str, bytes]) -> None:
    if VENDOR_DIR.exists():
        shutil.rmtree(VENDOR_DIR)
    for rel, data in sorted(desired.items()):
        out = VENDOR_DIR / rel
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_bytes(data)


def read_current_root_shims() -> dict[str, bytes]:
    """Root-level shims we previously generated, identified by the marker."""
    out: dict[str, bytes] = {}
    for path in sorted(SRC_DIR.glob("*.h")):
        data = path.read_bytes()
        if data.startswith(SHIM_MARKER.encode("utf-8")):
            out[path.name] = data
    return out


def write_root_shims(desired: dict[str, bytes]) -> None:
    for name in read_current_root_shims():
        if name not in desired:
            (SRC_DIR / name).unlink()
    for name, data in sorted(desired.items()):
        (SRC_DIR / name).write_bytes(data)


def write_lock(sha: str, ref: str, verbatim: int, shims: int) -> None:
    today = _dt.date.today().isoformat()
    LOCK_PATH.parent.mkdir(parents=True, exist_ok=True)
    LOCK_PATH.write_text(
        "# PCMFlowBluetooth — pinned upstream snapshot\n"
        "#\n"
        "# The vendored SBC codec under src/external/sbc/ is a verbatim subset of\n"
        "# ESP-IDF's components/bt/host/bluedroid/external/sbc/ (itself AOSP-derived),\n"
        "# plus generated shim headers. `tools/sync_sbc.py` reads this file to report\n"
        "# drift and rewrites it on every --apply run.\n"
        "#\n"
        "# Upstream tracking is level L0 — manual, never from CI. See SPEC.md §11.5.\n"
        "\n"
        "[sbc]\n"
        f'repo     = "espressif/esp-idf"\n'
        f'subdir   = "{UPSTREAM_SUBDIR}"\n'
        f'ref      = "{ref}"\n'
        f'commit   = "{sha}"\n'
        f'url      = "https://github.com/espressif/esp-idf/tree/{sha}/{UPSTREAM_SUBDIR}"\n'
        f'license  = "Apache-2.0"\n'
        f'synced   = "{today}"\n'
        f"# {verbatim} verbatim files + {shims} generated shim headers\n",
        encoding="utf-8",
    )


def main() -> int:
    args = parse_args()

    with tempfile.TemporaryDirectory() as tmpdir:
        src_root, sha = resolve_source(args, pathlib.Path(tmpdir))
        print(f"Upstream: {src_root} @ {sha}")

        verbatim = collect_upstream(src_root)
        shims = plan_shims(verbatim)
        root_shims = {k: v.encode("utf-8") for k, v in plan_root_shims(verbatim).items()}

        overlap = set(verbatim) & set(shims)
        if overlap:
            raise SystemExit(f"error: shim would overwrite a vendored file: {sorted(overlap)}")

        desired: dict[str, bytes] = dict(verbatim)
        desired.update({k: v.encode("utf-8") for k, v in shims.items()})

        total_shims = len(shims) + len(root_shims)
        print(f"{len(verbatim)} verbatim files, {len(shims)} shims, "
              f"{len(root_shims)} root shims")
        dirty = report(read_current(), desired)
        dirty |= report(read_current_root_shims(), root_shims)

        if not args.apply:
            print("\nDry run. Re-run with --apply to write.")
            return 0

        write_tree(desired)
        write_root_shims(root_shims)
        write_lock(sha, args.ref if not args.local else "local", len(verbatim), total_shims)
        print(f"\nWrote {VENDOR_DIR}, {len(root_shims)} root shim(s) in {SRC_DIR}, "
              f"and {LOCK_PATH}.")
        if not dirty:
            print("Contents were already up to date.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
