/* Generated by tools/sync_sbc.py - do not edit. */
/* Angle-bracket include of external/sbc/decoder/include/oi_codec_sbc_private.h — see tools/sync_sbc.py. */
#include "external/sbc/decoder/include/oi_codec_sbc_private.h"
